on:
  workflow_dispatch:
    inputs:
      sdl_version:
        description: 'Framework version'
        required: true
        default: '2.5.3'
      bash_file:
        description: 'Publish artifacts'
        required: true
        default: 'Port.sh'   

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.sdl_veersion }}"
        echo "Tags: ${{ github.event.inputs.bash_file }}" 
